# Generated by Django 3.2.9 on 2021-11-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeCloneAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.CharField(max_length=50),
        ),
    ]
